POSOman/Models/PurchaseReturn.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReturn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseReturn()
        {
            this.PurchaseReturnDetails = new HashSet<PurchaseReturnDetail>();
        }
    
        public int PurchaseReturnID { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseReturnDetail> PurchaseReturnDetails { get; set; }
    }
}

POSOman/Controllers/PurchaseReturnController.cs
using MangoERP.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;


namespace MangoERP.Controllers
{
    public class PurchaseReturnController : Controller
    {
        public dbPOS db = new dbPOS();
        public ActionResult Index1()
        {
            return View("Index", db.Purchases.Where(p => p.IsReturned == true ).ToList());

        //    return View("Index1", db.PurchaseReturns.Where(p =>  p.IsDeleted != true).ToList());
            //return View();
        }
        // GET: PurchaseReturn
        public ActionResult Index()
        {
            return View("Index", db.Purchases.Where(p => p.IsReturned == false  && p.GR !=null && p.IsDeleted != true).ToList());
            //return View();
        }
        public JsonResult getInvoiceDetails(int orderID)
        {
            if (orderID > 0)
            {
                try
                {
                    int branchId = 0;

                    if (Session["BranchID"] != null)
                    {
                        branchId = Convert.ToInt32(Session["BranchID"]);
                    }
                    else
                    {
                        var user = User.Identity;
                        string currentUserId = User.Identity.GetUserId();
                        var currentUser = db.AspNetUsers.FirstOrDefault(x => x.Id == currentUserId);
                        branchId = currentUser.BranchID;
                    }
                    var qry = db.PurchaseDetails.Where(p => p.PurchaseId == orderID)
                        .Select(p => new
                        {
                            
                            p.Purchase.TotalAmount,
                            p.Qty,
                            p.MaterailName,
                         
                            p.Price,
                            p.Amount,
                            p.Description,
                            p.MeasureOfUnit,
                       }).ToList();
                    return Json(new { qry }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    return Json(ex.Message.ToString());
                }

            }

            return Json("");

        }

        [HttpPost]
        //Edit Vendro 
        public JsonResult GrInvoice(int OrderId)
        {
            List<object> objectList = new List<object>();
            var ProductsList = db.PurchaseDetails.Where(x => x.PurchaseId == OrderId).Select(p => new { Price = p.Price, Qty = p.Qty, Description = p.Description, MeasureOfUnit = p.MeasureOfUnit, Amount = p.Amount, MaterailName = p.MaterailName, MaterailId = p.MaterailId }).ToList();

            var Order = db.Purchases.Where(x => x.Id == OrderId).FirstOrDefault();

            objectList.Add(new
            {
                PurchaseNo = Order.PurchaseNo,
                PostingDate = Order.PostingDate.ToString(),
                DocumnetDate = Order.DocumnetDate.ToString(),
                GRNO = Order.GR,
                ReferencePO = Order.ReferenceNumber,
                ProductsList = ProductsList


            });



            return Json(objectList, JsonRequestBehavior.AllowGet);

        }
        public ActionResult Create(int? Id)
        {
            var data = db.Purchases.Where(p => p.Id == Id).FirstOrDefault();
            ViewBag.Invoice = data?.PurchaseNo;
            ViewBag.VendorId = data?.VendorId;
            ViewBag.OrderId = Id;
            ViewBag.Total = data?.TotalAmount;

            // ViewBag.BranchID = branchId;
            ViewBag.vendor = data?.Vendor?.Vendor_Name;
            // ViewBag.vendorCode = db.Vendors.Select(v => new { Value = v.AccountID, Name = v.VendorCode }).ToList();
            ViewBag.Product = db.Products.Select(c => new { Value = c.Id, Name = c.MaterialName }).ToList();

            return View();
        }

        [HttpPost]
        public JsonResult ReturnPurchase(PurchaseReturn model, int? OrderId)
        {
            try
            {

                int branchId = 0;
                int userID = 0;
                string useridname = "";
                if (Session["BranchID"] != null && Session["UserID"] != null)
                {
                    branchId = Convert.ToInt32(Session["BranchID"]);
                    userID = Convert.ToInt32(Session["UserID"]);
                }
                else
                {
                    var user = User.Identity;
                    string currentUserId = User.Identity.GetUserId();
                    var currentUser = db.AspNetUsers.FirstOrDefault(x => x.Id == currentUserId);
                    branchId = currentUser.BranchID;
                    userID = currentUser.UserId;
                    useridname = currentUser.Id;
                }
              
                bool sucess = false;

                var ProductsList = db.PurchaseDetails.Where(x => x.PurchaseId == OrderId).ToList();
                int? qty = 0;
                foreach (var item in ProductsList)
                {
                    qty += item.Qty;
                }
                int? oldqty = 0;
                decimal? total = 0;
                foreach (var item in model.PurchaseReturnDetails)
                {
                    oldqty += item.Qty;
                    total = item.Qty * item.Price;
                }
                string data = "";
                if (qty == oldqty)
                {
                    sucess = true;
                    data = "No. of quantity in PO and Goods  Receipt are Equal";
                }
                if (qty > oldqty)
                {
                    sucess = true;
                    data = "No. of quantity in PO is Less";
                }
                if (qty < oldqty)
                {
                    data = "greater then No. of quantity in Goods Receipt";
                }

                model.TotalAmount = model.TotalAmount;
                model.UserID = useridname.ToString();
                model.PurchaseID = OrderId??0;
                model.IsDeleted = false;
                model.InvoiceNo = model.InvoiceNo;
               

                if (sucess)
                {
                    MangoERP.Models.BLL.OrderBookingBLL order = new Models.BLL.OrderBookingBLL();
                    object result = order.ReturnPurchase(model, OrderId);
                    return Json(result);
                }
                else
                {
                    return Json("Error");
                }
            }
            catch (Exception ex)
            {
                return Json("Error");

            }
        }


    }
}

POSOman/Views/PurchaseReturn/Index.cshtml
@model IEnumerable<MangoERP.Models.Purchase>
@{
    ViewBag.Title = "Index";
}
<style>
    .table th, .table td {
        padding: 0.75rem 1.2rem;
    }
</style>
<div class="content-body">
    <!-- DOM - jQuery events table -->
    <section id="dom">
        <div class="row">
            <div class="col-12">
                <h2>RETURN PURCHASE</h2> <br />
                <div class="card">
                    @using (Html.BeginForm("Save", "PurchaseReturn",
new { ReturnUrl = ViewBag.ReturnUrl },
FormMethod.Post, new { @class = "form form-horizontal striped-rows form-bordered" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="card-content collapse show">
                            <div class="card-body card-dashboard">
                                <div class="table-responsive">
                                    <table id="tblPO" class="table table-striped table-bordered alt-pagination">
                                        <thead>
                                            <tr>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.GR)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.PurchaseNo)
                                                </th>
                                                <th>
                                                    Vendor
                                                </th>
                                             
                                             
                                                
                                                @*<th>
                                                        <label>Payment Type</label>
                                                    </th>*@
                                              
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.GR)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.PurchaseNo)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Vendor.Vendor_Name)
                                                    </td>
                                                   

                                                    <!--<td>-->
                                                        @*@Html.ActionLink("Details","null",new { onclick = "getInvoiceDetails(" + item.OrderID + ");" })*@
                                                        <!--<a href="#" onclick="getInvoiceDetails(@item.Id); return false;">Details</a>
                                                    </td>-->
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions right">
                            <input type="button" id="btnSave" value="Save" class="btn btn-primary" />
                        </div>
                    }
                </div>
            </div>
        </div>
        <div class="row" style="display:none">
            <div class="col-12">
                <div class="card">
                    <div class="card-content collapse show">
                        <div id="dvtbl" class="table-responsive">
                            <table id="tbl" class="table">
                                <thead>
                                    <tr>
                                        @*<th></th>*@
                                        <th>ID</th>
                                        <th>Material Name.</th>

                                        <th>Qty</th>

                                        <th>Returned Qty</th>
                                        <th>Returning Qty</th>

                                        <th>Sub Total</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                                <tfoot>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td>Total</td>
                                        <td><input type="text" class="form-control input-sm" style="width:110px;" id="txtTotal" disabled /></td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@section scripts{
    <script type="text/javascript">
        $('#tblPO').DataTable();
    </script>
    @*<link rel="stylesheet" type="text/css" href="~/Content/vendors/css/extensions/toastr.css">
    <script src="~/Scripts/vendor/js/extensions/toastr.min.js"></script>
    <script src="~/Scripts/customScripts/general.js"></script>*@
    <script src="~/Scripts/purchase/Return_1.js"></script>
    @*<script src="~/Scripts/customScripts/helper.js"></script>*@
    <link rel="stylesheet" type="text/css" href="~/Content/vendors/css/extensions/sweetalert.css">

    <script src="~/Scripts/sweetalert.min.js" type="text/javascript"></script>
}

POSOman/Views/PurchaseReturn/Index1.cshtml
@model IEnumerable<MangoERP.Models.pur>

@{
    ViewBag.Title = "Index";
}


<div class="content-body">
    <section id="striped-row-form-layouts">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-content collpase show">
                        <div class="card-body">
                            <table class="table" id="table1">
                                <thead>
                                    <tr>
                                        <th>
                                            GR
                                        </th>
                                        <th>
                                            VendorName
                                        </th>

                                        <th>
                                            DocumnetDate
                                        </th>
                                        <th>
                                            PostingDate
                                        </th>
                                        <th>
                                            Amount
                                        </th>
                                        <th></th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.GR)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Vendor.Vendor_Name)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.DocumnetDate)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.PostingDate)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.TotalAmount)
                                            </td>


                                            <td>
                                                 
                                              
                                            </td>
                                        </tr>
                                    }
                                </tbody>

                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@section Scripts
    {
    <script type="text/javascript">



        $(document).ready(function () {
            $('#table1').DataTable();

        });
    </script>
}